### ISSUE TITLE
Refactor components and test them

### ISSUE THREAD

**Issue by erickrodrigs** [engsoft-2023/new-frontend#10]

**Comment by DerickWMFrias** [comment]
**To do:**

**Refatorar os componentes:**
- [ ]  DisplayMetrics
- [ ] Graph
- [ ] ImageKey
- [ ] MetricsWrapper
- [ ] RegisterSystemForm

**Levar os arquivos do diretório hook para os diretórios correspondentes**

Na refatoração:
- Adicionar testes
- Adicionar tipos no TypeScript
- Transferir a lógica das pages para views
